name = "adonis-odm-docs"
compatibility_date = "2024-01-15"

# For static sites, we don't need most of the server configuration
# This file is mainly for local development with wrangler

# Local development configuration
[dev]
port = 8788
local_protocol = "http"

# Build configuration (mainly for reference)
# Cloudflare Pages will use the build command from package.json
# Build command: npm run build
# Build output directory: dist
